services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_VER=20.13.1
    tty: true
    volumes:
      - ./backend:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - 3000:3000

volumes:
  node_modules:
